title: The Open Source Divinity School
description: A secular-friendly, open source resource for a modern education in divinity.
google_analytics: TODO
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
