title: The Open Source Divinity School
description: Secular-friendly, open-source resources for a modern divinity education.
google_analytics: UA-43720588-1
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
